### ISSUE TITLE
[BUG] - Correction orthographique + bug thème page accueil

### ISSUE THREAD

**Issue by X3R0-FR** [CraftMyWebsite/theme-wipe#2]
Correction orthographique :
![image](https://github.com/user-attachments/assets/e4317102-513f-4315-98e3-5a2f30ecea19)

Bug avec les messages pour cacher :
https://github.com/user-attachments/assets/2a3184d0-db82-4178-8f5b-9a2b12331f80

**Comment by Zomblard** [comment]
Fixed : https://github.com/CraftMyWebsite/theme-wipe/commit/d5401753f559114cb1f4cee7728d7aa6e9298a2c
