### ISSUE TITLE
[FEATURE REQUESTS] - Ajout du package Newsletter

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/theme-wipe#3]
# 🛠️ Feature requests

## Feature Description

Actuellement avec le thème Wipe nous n'avons aucun moyen de nous inscrire à la Newsletter
il serait cool d'avoir plusieurs endroits pour s'y inscrire 

Je propose : 

Lors de l'inscription 
mais aussi sur le profil (et pouvoir du coup s'en désinscrire) 

## Intended Use

Possibilité de s'inscrire à la Newsletter et recevoir la communication du site

## Justification

Pour mieux communiquer et parce que actuellement c'est impossible

**Comment by Zomblard** [comment]
Added : https://github.com/CraftMyWebsite/theme-wipe/commit/3fb8676d0205d5ab04537a4684280e85137b1485
