### ISSUE TITLE
[BUG] - Page /cookies inexistante 

### ISSUE THREAD

**Issue by Emilien52** [CraftMyWebsite/theme-wipe#4]
# 🐞️ Bug report

## Environment
- CMW Version: Alpha-02
- Resource Version: 1.0.1 (ou "Simple-Cookies") 

## Bug Description
Page /cookies inexistante 

## Steps to Reproduce the Bug

Ajouter /cookies à son url 

## Additional Information
https://github.com/Overheat-Studio-Community/cmw-package-simple-cookies/wiki/How-to-use#step-22---mainviewphp

**Comment by Zomblard** [comment]
Fixed : https://github.com/CraftMyWebsite/theme-wipe/commit/e3194f1fda2e5827472f60d145d0cc30838c4548
